"""Add boolean lengthened partial field to exercise_muscle table

Revision ID: 33e61260c370
Revises: 40d1eb2ee63d
Create Date: 2026-05-21 18:47:17.515424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e61260c370'
down_revision: Union[str, Sequence[str], None] = '40d1eb2ee63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
